name: "dbt_snowflake_pipeline"
version: "1.0.0"
profile: "dbt_snowflake_pipeline"

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
seed-paths: ["seeds"]

models:
  dbt_snowflake_pipeline:
    # --- 1. Bronze Layer (Raw Ingestion) ---
    bronze:
      +database: BRONZE_PRODUCTION
      +schema: landing # Becomes 'LANDING' in Prod
      +materialized: table # Physical storage for raw data

    # --- 2. Silver Layer (Cleaned & Transformed) ---
    silver:
      +database: SILVER_PRODUCTION
      +schema: intermediate # Becomes 'INTERMEDIATE' in Prod
      +materialized: view # Virtual layer to save on storage

    # --- 3. Gold Layer (Business Intelligence) ---
    gold:
      +database: GOLD_PRODUCTION
      +schema: analytics # Becomes 'ANALYTICS' in Prod
      +materialized: table # Optimized for dashboard performance

seeds:
  dbt_snowflake_pipeline:
    +database: BRONZE_PRODUCTION
    +schema: raw_seeds
