dbt_snowflake_pipeline:
  target: dev # This is the default for local development
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      database: '"{{ env_var("SNOWFLAKE_DATABASE") }}"'
      schema: '"{{ env_var("SNOWFLAKE_SCHEMA") }}"'

    # Add the production target here
    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      database: '"{{ env_var("SNOWFLAKE_DATABASE") }}"'
      schema: '"{{ env_var("SNOWFLAKE_SCHEMA") }}"'
